//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAccounting.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketAccounting_DBEntities : DbContext
    {
        public MarketAccounting_DBEntities()
            : base("name=MarketAccounting_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SlAndBu> SlAndBu { get; set; }
        public virtual DbSet<TypeId> TypeId { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<PWYBF> PWYBF { get; set; }
    }
}
